apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u9938jfqb-go 
  janus-idp.io/tekton: u9938jfqb-go
  backstage.io/kubernetes-id: u9938jfqb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u9938jfqb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml